// <auto-generated />
using System;
using DeliveryWebLoL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliveryWebLoL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260226044559_AddUserVerifications")]
    partial class AddUserVerifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeliveryWebLoL.Models.Delivery", b =>
                {
                    b.Property<Guid>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DriverUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VehicleInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryID");

                    b.HasIndex("DriverUserID");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.DeliveryStop", b =>
                {
                    b.Property<Guid>("StopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeliveryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EstimatedArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("StopID");

                    b.HasIndex("DeliveryID");

                    b.HasIndex("OrderID");

                    b.ToTable("DeliveryStops");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Inventory", b =>
                {
                    b.Property<Guid>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InventoryID");

                    b.HasIndex("ItemID");

                    b.HasIndex("LocationID");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Item", b =>
                {
                    b.Property<Guid>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ItemCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ItemID");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Location", b =>
                {
                    b.Property<Guid>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerUserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LocationID");

                    b.HasIndex("OwnerUserID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DestinationLocationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<Guid>("RequestedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceLocationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("ApprovedByUserID");

                    b.HasIndex("DestinationLocationID");

                    b.HasIndex("RequestedByUserID");

                    b.HasIndex("SourceLocationID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.OrderLineItem", b =>
                {
                    b.Property<Guid>("LineItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LineItemID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderLineItems");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("VerifyExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Delivery", b =>
                {
                    b.HasOne("DeliveryWebLoL.Models.User", "DriverUser")
                        .WithMany("Deliveries")
                        .HasForeignKey("DriverUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DriverUser");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.DeliveryStop", b =>
                {
                    b.HasOne("DeliveryWebLoL.Models.Delivery", "Delivery")
                        .WithMany("DeliveryStops")
                        .HasForeignKey("DeliveryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryWebLoL.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Inventory", b =>
                {
                    b.HasOne("DeliveryWebLoL.Models.Item", "Item")
                        .WithMany("Inventories")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryWebLoL.Models.Location", "Location")
                        .WithMany("Inventories")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Location", b =>
                {
                    b.HasOne("DeliveryWebLoL.Models.User", "OwnerUser")
                        .WithMany("Locations")
                        .HasForeignKey("OwnerUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Order", b =>
                {
                    b.HasOne("DeliveryWebLoL.Models.User", "ApprovedByUser")
                        .WithMany("ApprovedOrders")
                        .HasForeignKey("ApprovedByUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeliveryWebLoL.Models.Location", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryWebLoL.Models.User", "RequestedByUser")
                        .WithMany("RequestedOrders")
                        .HasForeignKey("RequestedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryWebLoL.Models.Location", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("DestinationLocation");

                    b.Navigation("RequestedByUser");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.OrderLineItem", b =>
                {
                    b.HasOne("DeliveryWebLoL.Models.Item", "Item")
                        .WithMany("OrderLineItems")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryWebLoL.Models.Order", "Order")
                        .WithMany("OrderLineItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Delivery", b =>
                {
                    b.Navigation("DeliveryStops");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Item", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("OrderLineItems");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Location", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.Order", b =>
                {
                    b.Navigation("OrderLineItems");
                });

            modelBuilder.Entity("DeliveryWebLoL.Models.User", b =>
                {
                    b.Navigation("ApprovedOrders");

                    b.Navigation("Deliveries");

                    b.Navigation("Locations");

                    b.Navigation("RequestedOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
